version: '2'
services:
   db:
     image: postgres:9.5
     ports:
       - "5432:5432"
     volumes:
       - ~/data:/var/lib/postgresql/data
   web:
     build:
       context: .
       dockerfile: roboadvisor_dockerfile
     environment:
       - DJANGO_SETTINGS_MODULE=app.setting_postgres
     command: python3 manage.py runserver 0.0.0.0:8000
     ports:
       - "80:8000"
     depends_on:
       - db
   sentiment:
     build:
       context: .
       dockerfile: sentiment_dockerfile
     environment:
       - DJANGO_SETTINGS_MODULE=robo_app.prod_settings
     depends_on:
       - db      
   prediction:
     build:
       context: .
       dockerfile: prediction_dockerfile
     depends_on:
       - db
